apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  # namespace: default
  name: owasp-juice-shop
spec:
  securityPolicy:
    name: juice-shop-cloud-armor-policy
---
apiVersion: v1
kind: Service
metadata:
  name: owasp-juice-shop
  # namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "owasp-juice-shop"}'
spec:
  ports:
  - name: http-juice-sho
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: owasp-juice-shop
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: ingress-cert
spec:
  domains:
    - juice-showasp.duckdns.org
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
 name: ingress-fe-config
spec:
 redirectToHttps:
   enabled: true
   responseCodeName: PERMANENT_REDIRECT
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: owasp-juice-shop
  annotations:
    kubernetes.io/ingress.class: "gce"
    # kubernetes.io/ingress.global-static-ip-name: "ingress-test-ip"
    networking.gke.io/managed-certificates: "ingress-cert"
    networking.gke.io/v1beta1.FrontendConfig: "ingress-fe-config"
spec:
  defaultBackend:
    service:
      name: owasp-juice-shop
      port:
        number: 80
